### ISSUE TITLE
initial setup

### ISSUE THREAD

**Issue by chandsharma** [OmkarK45/blog-app#1]
how to setup this project initially.
need some KEYs in ".env" file.
but there is no guide to do that.
how to setup and add mongo db cloud in this to work

**Comment by OmkarK45** [comment]
Hi ! Apologies for absence of a Readme. 

Create a .env file in root of the backend

Include the following variables.

```
ACCESS_TOKEN=74b21ccab0bc708d6e805b34722c432a566a2ed4752effc2f5a92620ef2a94d1419db88a48da3fee0cc94623ef97a53782f51b25c1da7a2fe72b840733bade45

REFRESH_TOKEN_SECRET=50963fa8d344af8eb1c4b6ef69573e3f798139956165d35d6c533c24c5b0ec6b9ad33b49b25010631b0e3351ca5eaf8e260357a3c633defaa3684be2919c1af7

JWT_SECRET=6e955f69d09f2db9e1sdcb9e875b30a7f838867411159647c2635d7a5a2fede24dadf311db925eba16f08e2255cef54

DB_URI_LOCAL=mongodb://localhost/blog_db

DB_URI_ATLAS=mongodb+srv://<mongodb atlas username>:<mongodbatlast password>@xxxxxx.xxxxx.mongodb.net/your_db_name?retryWrites=true&w=majority
```
You can get MongoDB URL from MongoDB Atlas 
https://docs.mongodb.com/guides/cloud/connectionstring/

Change `JWT_SECRET` `ACCESS_TOKEN` and refresh token secrets to some other strong secrets.

**Comment by mehranrahnama** [comment]
hi 
other variables like REACT_APP_BACKEND are absent in .env file and project don,t run

**Comment by OmkarK45** [comment]
> hi other variables like REACT_APP_BACKEND are absent in .env file and project don,t run

Create `PORT` env in backend. Give value as 5000
Create `REACT_APP_BACKEND` on frontend give value as http://localhost:5000
